### ISSUE TITLE
Toevoegen Test-QC1f

### ISSUE THREAD

**Issue by gilsvda** [rivm-syso/KRWQCprotocol#26]
temperatuur staat ook nog genoteerd als t_5__veld in de test data van lmg en staat wel in de BRO parameterlijst als "Temperatuur" (zie https://broprogramma.github.io/GAR/#detail_class_Model_Parameterlijst)

**Comment by florisnaus** [comment]
Is deze test al geschreven?

**Comment by jspijker** [comment]
De functie QC1f lijkt niet goed te werken. Als ik negatieve waarden toevoeg aan de data, dan worden deze niet als 'verdacht' aangemerkt.

**Comment by florisnaus** [comment]
@gilsvda kan jij checken of je kan vinden wat er mis gaat?

**Comment by gilsvda** [comment]
Bij mij gaat het wel goed als ik ergens een negatieve waarde toevoeg. Wel wordt "temperatuur" uitgezonderd. Als iemand nu "Temperatuur" gebruikt werkt dat niet. Misschien een tolower toevoegen? Ik zal eerst even kijken of ik de test kan schrijven.

**Comment by jspijker** [comment]
Afgerond met #56
