### ISSUE TITLE
QC1f: Parameters definiëren welke wel negatieve waarden kunnen hebben

### ISSUE THREAD

**Issue by LoutK** [rivm-syso/KRWQCprotocol#37]
Gelieve in het script een lijst parameters te definiëren die wel een negatieve waarde kunnen hebben. Niet temperatuur (wordt al elders getest) maar wel isotopen en redoxpotentiaal. Deze parameters uitzonderen van de negatieve-waarde-test.

**Comment by gilsvda** [comment]
Isotopen en redoxpotentiaal zijn niet relvant voor het KRWQC protocol en moeten dus voorafgaand bij het klaarmaken van de data niet worden meegenomen.
