### ISSUE TITLE
Krijg het wegschrijven en samenvoegen van testoordelen niet werkend

### ISSUE THREAD

**Issue by LoutK** [rivm-syso/KRWQCprotocol#39]
Als ik het goed begrijp is het de bedoeling dat er na elke test de oordelen weg worden geschreven naar de metingen tabel. Het wegschrijven van de oordelen naar de metingen tabel krijg ik niet werkend.
Of ik krijg geen error, en wordt er ook niks weggeschrijven.
Of ik krijg de volgende error: 
`Error in qcout_add_oordeel(obj = d_metingen, test = test, oordeel = sort(unique(resultaat_df$oordeel))[1],  : 
  qcout_add_oordeel: onbekend oordeel toegevoegd`

Daarnaast vroeg ik mij af of ik de resultaten van een QC juist wel of niet moet wegschrijven naar een variabele? Wellicht dat dat er nog iets mee te maken heeft.

**Comment by gilsvda** [comment]
De vignette is vandaag (11-2-2022) geupdate met het updaten van de master. De vignette bevat nu meer voorbeelden voor het uitvoeren van de tests. Voor de vignette zie: [https://rivm-syso.github.io/KRWQCprotocol/articles/krwqcprotocol.html](url).

Het uitvoeren van bijvoorbeeld QC0a zoals in het voorbeeld hieronder hangt het resultaat als atribute aan x (het metingen bestand). x Is hier dus een combinatie van het metingen bestand en het oordeel dat daar aan vast is gemaakt (het vastmaken van atributes aan x is **niet** gelimiteerd tot 1 QC test).
```{r eval = FALSE}
x <- metingen

x <- QC0a(d_veld = veld, d_put = put, d_metingen = x, verbose = TRUE)
```
Mocht je geinteresseerd zijn in het bekijken van deze atributes dan kan dat met onderstaande code (dit kan alleen na het uitvoeren van QC0a).
```{r eval = FALSE}
xattr <- attr(x, "qcout")
xattr$QC0a
```
