### ISSUE TITLE
QC0h: berekeningen klappen eruit als er een NULL waarde de input is

### ISSUE THREAD

**Issue by LoutK** [rivm-syso/KRWQCprotocol#40]
Bij het rekenen met de no3 en so4f waardes klappen de berekeningen eruit als er een NULL waarde door komt. (https://github.com/jspijker/KRWQCprotocol/blob/f91925a1b2353d31620b5f1c05bae2c3e5a54e18/R/QC0h.R#L54-L62)

Error log:
`i `no3_waarde = no3_waarde * 4.4268`.
x non-numeric argument to binary operator`

**Comment by gilsvda** [comment]
QC0h is vandaag (11-2-2022) geupdate bij het updaten van de master. Deze berekening was enkel voor het omrekenen van NO3-N naar NO3. Deze berekening is niet meer relevant omdat NO3 ingevoerd dient te worden als NO3 en niet als NO3-N. 

Toch staat er in QC0h nog een check op no3_n_waarde om die om te rekenen. Dit heeft geen invloed op de rest van QC0h maar moet wel voor de netheid worden verwijderd.
