### ISSUE TITLE
QC3h: Functie neemt waarden mee in de test welke hier niet van belang zijn

### ISSUE THREAD

**Issue by LoutK** [rivm-syso/KRWQCprotocol#41]
In QC3h wordt er (o.a.) getest of er niet meer dan twee waarden voor no3 en nh4 voorkomen in de parameter tabel. In onze dataset zit echter ook de stof 'glufsntnh4'. Hierdoor is het aantal keer dat het script no3 of nh4 vindt >2, en stopt hij er mee. 'glufsntnh4' staat echter los van deze test.
https://github.com/jspijker/KRWQCprotocol/blob/f91925a1b2353d31620b5f1c05bae2c3e5a54e18/R/QC3h.R#L30-L32

**Comment by LoutK** [comment]
Bedankt voor de aanpassing, maar helaas komt het nog steeds voor bij "glufsntNH4" en "Organ. geb. -NH4".
Het vooraf verwijderen van de niet-relevante parameters heeft niet onze voorkeur.
Is het misschien handiger om in plaats van:
```
   d <- d_metingen %>%
        dplyr::filter(stringr::str_detect(parameter, "NO3|NH4")) 
```

 dit te gebruiken:
```
   d <- d_metingen %>%
        dplyr::filter(parameter %in% c("NO3","NH4")) 
```

**Comment by gilsvda** [comment]
Ik denk dat de str_detect in het verleden een bepaalde functie had en nu we met de aquocodes werken niet meer. Ik ga dit vanmiddag bespreken en kijken of de aanpassing in lijn is met de bedoeling van het protocol.

**Comment by jspijker** [comment]
Klopt, die str_detect heeft een functie in onze LMG data. Nu met aquocodes is dit niet meer relevant. Ik stel voor om het voorstel van @LoutK over te nemen. 
Omdat dit een use case is die we niet voorzien hadden stel ik voor dat ik eerst kijk hoe het probleem kan reproduceren in de regressie tests en dan dat jij, @gilsvda, dan bovenstaande implementeerd. Weten we meteen of het goed is gedaan.

**Comment by gilsvda** [comment]
afgerond met #65
