### ISSUE TITLE
Oordeel 'test niet uitvoerbaar' toevoegen wanneer er waardes van stoffen ontbreken

### ISSUE THREAD

**Issue by LoutK** [rivm-syso/KRWQCprotocol#60]
Bij verschillende tests (QC0h, QC3c, QC3e, QC3f, QC3g) stoppen de scripts bij berekeningen zoals bij regel 53+54 in QC3f:
```
    dplyr::mutate(oordeel = ifelse(abs(pH - pH_veld) >= 2,
                                   "twijfelachtig", "onverdacht"),
```
De reden hiervoor is dat (in dit geval) 'pH' en/of 'pH_veld' geen waarde heeft.  Dat resulteert erin dat het script stopt en een foutmelding geeft:
`non-numeric argument to binary operator`

Dit gedrag komt ook voor bij bovenstaande QC's, maar dan in andere berekeningen. 

Het script zou het oordeel 'test niet uitvoerbaar' moeten teruggeven wanneer de test om zo'n dergelijke reden faalt.
Naar mijn inziens komt dit eruit te zien als een standaard check welke in veel tests terug moet komen.
In een 'luxe' versie van een QC wordt dan ook meteen verteld welke parameters er geen waarde hebben, maar dat is voor nu denk ik bijzaak.

**Comment by gilsvda** [comment]
Dit zullen we vanmiddag bespreken. In principe is het teruggeven van alle informatie m.b.t. een QC-oordeel (zoals niet uitvoerbaar) terug te vinden in de attributes van het metingen bestand. Als we niet uitvoerbaar voor deze tests toevoegen zal de informatie die je zoekt dus ook terug te vinden zijn en waarschijnlijk dan ook worden gegeven als je "verbose = TRUE" toevoegd aan de QC tests.

**Comment by jspijker** [comment]
We gaan een aparte functie opstellen die in genoemde testfuncties controleert of voor iedere meting alle benodigde parameters aanwezig zijn. Het resultaat van die functie zijn de id's van de incomplete metingen. Deze id's krijgen dan in de test functie het oordeel 'niet uitvoerbaar', in de testfunctie worden de incomplete metingen verwijderd voordat de test verder gaat. Eventueel geven we een tabel met de incomplete metingen terug via het resultaat attribute.

Daarbij moeten we ook controleren of het resultaat 'niet uitvoerbaar' ook mag volgens het protocol.

Naast de nieuwe functie stellen we ook een paar testfuncties op om de werking te controleren.

**Comment by jspijker** [comment]
Tests voor nieuwe functionaliteit in QC0h, QC3c, QC3f, QC3g, en QC3e toegevoegd. @gilsvda de test voor QC3e geeft nu een error omdat de functio qcidNietUitvoerbaar nog niet is opgenomen in de functie, dus de test faalt.

**Comment by gilsvda** [comment]
@jspijker als het goed is heb ik die toegevoegd bij [e772c49](https://github.com/rivm-syso/KRWQCprotocol/commit/e772c499ccdde302dc8871417903ba9e1e546dc0)

**Comment by gilsvda** [comment]
@jspijker EC is nog niet opgenomen als een van de te controleren kolommen op NA in QC3e en waarschijnlijk ook in QC3c. Ga ik oplossen

**Comment by gilsvda** [comment]
Update QC3e (ik was de #60 vergeten) [160cf2b](https://github.com/rivm-syso/KRWQCprotocol/pull/61/commits/160cf2be5f5a79ca0ba17bc22d2a4b2846069851)
Was natuurlijk niet nodig voor QC3e want de ionenbalans heeft geen ec nodig

**Comment by jspijker** [comment]
Na commit [6b22b62](https://github.com/rivm-syso/KRWQCprotocol/commit/6b22b62c50f3a4675700c35460648108ae96dbba) gaat er nu iets mis in test QC4a T2

**Comment by gilsvda** [comment]
Het verwijderen van dubbele metingen bij de commit [6b22b62](https://github.com/rivm-syso/KRWQCprotocol/commit/6b22b62c50f3a4675700c35460648108ae96dbba) in het metingen bestand zorgt er voor dat de 1e6 o.i.d. niet meer boven de z-score 3.5 uitkomt als ik mij niet vergis.

**Comment by gilsvda** [comment]
@LoutK de melding `non-numeric argument to binary operator` wordt veroorzaakt door het uitvoeren van een 'binary operation' op iets wat geen nummer is (zie ook [deze pagina van stackoverflow](https://stackoverflow.com/questions/29665428/non-numeric-argument-to-binary-operator-error-in-r)). Als het goed is gaat het script niet stuk bij geen waarde (NA), zeker niet na komende update. Maar wel als de waardes bijvoorbeeld als character staan (bijv. "<10" of "10,0"). Als je wilt kan ik ook een keer meekijken bijvoorbeeld via Teams.

**Comment by gilsvda** [comment]
afgerond met #61
