### ISSUE TITLE
QC4a onvoldoende gevoelig om afwijkingen te herkennen

### ISSUE THREAD

**Issue by jspijker** [rivm-syso/KRWQCprotocol#62]
Test QC4a T2 geeft een fail. QC4a is niet gevoelig genoeg om de afwijking in de test te herkennen.  We moeten QC4a dus nalopen of de berekening van de zscores kloppen.

In de master versie gaat de test nog goed. In de issue60 branch geeft de test een fail

**Comment by gilsvda** [comment]
Opgelost in [9ebb33e](https://github.com/rivm-syso/KRWQCprotocol/commit/9ebb33e486465d59e19615b72c90daaa90b093d5)
