### ISSUE TITLE
iden heeft geen filter in zich (probleem voor iig QC3d)

### ISSUE THREAD

**Issue by florisnaus** [rivm-syso/KRWQCprotocol#77]
De selectie van de juiste monsters voor het toevoegen van het resultaat (gaat obv (iden = paste(putcode, jaar, maand, dag, sep = "-")) heeft geen filter in zich. Voor in ieder geval QC3d worden hierdoor alle filters van een put afgekeurd ipv alleen het filter waar de fout zit.

Mogelijk gaat dit voor andere QCs ook fout.

**Comment by gilsvda** [comment]
afgerond met #86
