### ISSUE TITLE
Update nummering van de testen

### ISSUE THREAD

**Issue by florisnaus** [rivm-syso/KRWQCprotocol#90]
In 2023/2024 is het KRWQC protocol geüpdatet. Hierbij zijn ook wijzigingen in de nummering van de tests doorgevoerd. Deze wijziging in de nummering van de tests moet ook in de scripts worden doorgevoerd. 

Een overzicht van te wijzigen nummers:

test | Nieuw QC nummer | Oud QC nummer (dus ook in de   scripts)
-- | -- | --
QC0 |   |  
X, y coördinaten | QC0a | QC0a
landgebruik | QC0b | QC0b
Beschadiging | QC0c | QC0c
Afdekking put | QC0d | QC0d
Controle filter | QC0e | QC0e (en QC0f)
Controle zoet/zout | QC0f | QC0g
Redox klasse | QC0g | QC0h
  |   |  
QC1 |   |  
datum | QC1a | QC3a
registratie BRO | QC1b | QC3b
parameterlijst BRO | QC1c | QC1a
apparaat, techniek & procedure | QC1d | QC1b
rapportagegrens | QC1e | QC1c
conformiteit BRO-dataformaat | QC1f | QC1d
Controle analysegegevens | QC1g | QC1e
Negatieve waardes | QC1h | QC1f
  |   |  
QC2 |   |  
Toestroming filter | QC2a | QC2a
Conformiteit bemonsteringsprocedure | QC2b | QC2b
Veldwaarnemingen | QC2c | QC2c
  |   |  
QC3 |   |  
Beoordeling consistentie historie | QC3a | QC4a
Controle filterverwisselingen | QC3b | afwezig
  |   |  
QC4 |   |  
Ionenbalans | QC4a | QC3c
EC-veld & EC-lab | QC4b | QC3d
EC-gemeten & EC-berekend | QC4c | QC3e
Technisch waardebereik | QC4d | QC4b
Controle pH-veld & pH-lab | QC4e | QC3f
pH & HCO3 | QC4f | QC3g
NO3 & NH4 | QC4g | QC3h

**Comment by gilsvda** [comment]
Afgerond met #91
